name: Run parallel algorithm
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    continue-on-error: true
    env:
      matrix_size: 5000
    strategy:
      matrix:
        number_processors: [ 1, 2, 4 ]
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Install MPICH
      run: sudo apt install mpich
    - name: Build project
      run: |
        mpicc -O3 -o allshortestpair MyMPI.c allshortestpair.c -lm
        mpicc -O3 -o gen_adj_matrix gen_adj_matrix.c
    - name: Run project
      run: |
        ./gen_adj_matrix $matrix_size ./$matrix_size.bin
        mpiexec -n ${{ matrix.number_processors }} ./allshortestpair ./$matrix_size.bin
