name: CI workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install mpich library
      run: sudo apt install mpich
    - name: make
      run: make all
