name: CI workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install mpich library
      run: sudo apt install mpich
    - name: build
      run: |
        mpicc -O3 -o allshortestpair MyMPI.c allshortestpair.c -lm
        mpicc -O3 -o allshortestpair gen_adj_matrix.c
    - name: exec matrix 1000x1000
      run: mpiexec -n 4 ./allshortestpair ./matrices/1000.bin
